### ISSUE TITLE
Option to Disable Worldgen

### ISSUE THREAD

**Issue by Darkosto** [Glitchfiend/BiomesOPlenty#1972]
### Overview

Hello!

I'm creating a modpack right now that takes place fully underground using a custom datapack. I would to use Biomes o' plenty especially for all the decorative blocks. But currently, I cannot do that due to the dependency of TerraBlender. Terrablender overwrites many of my custom datapack settings such as biomes I have disabled (oceans, beaches) and skybox settings. Would you consider creating a BoP version that has no worldgen associated with it and only the blocks? I'm making this issue on this tracker because there is already a similar issue on the Terrablender tracker.

Thanks for your time!
Darkosto

### Why would this feature be useful?

This would allow devs to use the robust vanilla datapack features to their fullest extent whilst using Biomes o Plenty's blocks.

**Comment by Adubbz** [comment]
You can already disable TerraBlender replacing the default world type in its config file which will cause nothing to generate.

**Comment by Darkosto** [comment]
`	#Whether to replace the default built-in world types with our own.
	replace_default_worldtypes = false
`

I'm assuming you're talking about that config option? Unfortunately, that is not working for me. I've had that option off and test over the course of a week now with no luck.

**Comment by Adubbz** [comment]
If your config file looks like the above then you've commented out where you set the option to false, so that won't work

**Comment by Darkosto** [comment]
```toml
#General settings
[general]
	#Whether to replace the default Nether with our own.
	replace_default_nether = false
	#Whether to replace the default built-in world types with our own.
	replace_default_worldtypes = false
```


No, it is not commented out. That is how it was pasted into github.
